# M5a extensions — reproduction

Loads the two M5a extension experiments (neg α on `textured/ground/both` and label=ball on `line/blank/none`) and prints the key tables. Depends on M5a outputs already being present at `outputs/mvp_full_20260424-094103_8ae1fa3d/`.

- Design spec: `docs/superpowers/specs/2026-04-24-m5a-extensions-design.md`
- Run log: `docs/experiments/m5a_ext_neg_alpha_and_label.md`
- Insight: `docs/insights/m5a_ext_bidirection_and_label.md`

In [1]:
import sys
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from physical_mode.metrics.first_letter import extract_first_letter

RUN = PROJECT_ROOT / "outputs" / "mvp_full_20260424-094103_8ae1fa3d"
EXP1 = RUN / "steering_experiments" / "neg_alpha_textured_ground_both"
EXP2 = RUN / "steering_experiments" / "ball_line_blank_none"

## Experiment 1 — negative α

In [2]:
df1 = pd.read_parquet(EXP1 / "intervention_predictions.parquet")
print("n =", len(df1))
fl1 = (
    df1.groupby(["layer", "alpha", "first_letter"])
       .size()
       .unstack("first_letter", fill_value=0)
)
fl1

n = 50

first_letter   A  other
layer alpha
10    -40.0   10      0
      -20.0   10      0
      -10.0   10      0
      -5.0    10      0
       0.0     9      1

In [3]:
for a in sorted(df1["alpha"].unique()):
    r = df1[df1["alpha"] == a].iloc[0]
    text = r["raw_text"].replace("\n", " ")[:180]
    print(f"α={a:>6}: first={r['first_letter']}  :: {text}")

α= -40.0: first=A  :: A  The image depicts a ball falling towards a flat surface, which is a common representation of an object in motion under gravity. The ball's trajectory suggests it is moving downw
α= -20.0: first=A  :: A  Justification: The image depicts a ball above a line with a downward arrow pointing towards it, suggesting motion downwards. Therefore, the most logical conclusion is that the b
α= -10.0: first=A  :: A  The image depicts a ball with a downward arrow pointing towards a surface, suggesting that the ball will fall down if it is released from its current position.
α=  -5.0: first=A  :: A  The image depicts a ball with a downward arrow pointing towards a surface, indicating that the ball will fall down due to gravity.
α=   0.0: first=A  :: A  The image depicts a ball falling towards a surface, indicated by the downward arrow. Therefore, the most logical conclusion is that the ball will fall down to the surface.

## Experiment 2 — label=ball

In [4]:
df2 = pd.read_parquet(EXP2 / "intervention_predictions.parquet")
print("n =", len(df2))
fl2 = (
    df2.groupby(["layer", "alpha", "first_letter"])
       .size()
       .unstack("first_letter", fill_value=0)
)
fl2

n = 50

first_letter   A   D
layer alpha
10    0.0      0  10
      5.0      0  10
      10.0     0  10
      20.0     0  10
      40.0    10   0

In [5]:
for a in sorted(df2["alpha"].unique()):
    r = df2[df2["alpha"] == a].iloc[0]
    text = r["raw_text"].replace("\n", " ")[:180]
    print(f"α={a:>6}: first={r['first_letter']}  :: {text}")

α=   0.0: first=D  :: D  The image is an abstract representation of a circle and does not depict a physical object like a ball that can fall, move, or stay still. Therefore, it cannot be described in te
α=   5.0: first=D  :: D  The image is an abstract representation of a circle and does not depict a physical object like a ball that can fall, move, or stay still. Therefore, it cannot be described in te
α=  10.0: first=D  :: D  The image is an abstract representation and does not depict a physical object like a ball that can fall, move, or stay still. Therefore, it cannot be described in terms of physi
α=  20.0: first=D  :: D  The image depicts an abstract shape that does not represent a physical object like a ball. Therefore, it cannot be described in terms of physical motion such as falling, staying
α=  40.0: first=A  :: A) It falls down.  Justification: The ball is subject to gravity, which causes it to fall downward. This is a fundamental principle of physics and can be observed in everyday life,

## Compare with M5a baseline

In [6]:
base = pd.read_parquet(RUN / "steering_experiments" / "intervention_predictions.parquet")
base10 = base[(base["layer"] == 10)].copy()
base10["first_letter"] = base10["raw_text"].apply(extract_first_letter)
m5a_pivot = (
    base10.groupby(["alpha", "first_letter"])
          .size()
          .unstack("first_letter", fill_value=0)
)
print("M5a baseline (circle × line/blank/none × L10):")
m5a_pivot

M5a baseline (circle × line/blank/none × L10):

first_letter   B   D
alpha
0.0            0  10
5.0            0  10
10.0           0  10
20.0           0  10
40.0          10   0